### ISSUE TITLE
Cannot reproduce milepost project via given tutorial

### ISSUE THREAD

**Issue by hydai** [ctuning/reproduce-milepost-project#3]
Hi,
I followed README to get Milepost GCC. But I got some error.

My environment:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
```

Here is the script I used:

```
$ pip install ck
$ sudo apt-get install m4
$ sudo apt-get install build-essential automake autoconf libncurses-dev uuid-runtime
$ ck pull repo:reproduce-milepost-project
$ ck install package:compiler-ctuning-cc-2.5-src
```

When I type `ck install package:compiler-ctuning-cc-2.5-src`, the ck reports the following error messages:

https://gist.github.com/hydai/9a7aee806e438e45600d3aa84ec43277

**Comment by gfursin** [comment]
Hi,

It's now becoming increasingly difficult to rebuild MILEPOST GCC on the 
latest environment and with latest packages.

I remember that Abdul (in CC) had related problems. Abdul, do you 
remember how did you fix that? Can you help with that, please?

I am now very busy with current projects, but I see two longer-term 
solutions:
* provide a Docker image to build MILEPOST GCC
* add feature extractor plugin to LLVM (or latest GCC) which will not 
only extract sematic features but also call graphs
and information about loop iteration space - this can be a collaborative 
research project which we can help with ...

Cheers,
Grigori

**Comment by gfursin** [comment]
Hi again,

I tried to check installation on a clean Ubuntu 16.04.03 using Docker
and it seems that I didn't specify all the dependencies that may result 
in this crash.

I now added Docker image which builds MILEPOST GCC:
* 
https://github.com/ctuning/reproduce-milepost-project/blob/master/docker/ck-milepost-gcc-ubuntu16.04/Dockerfile

Basically, I install the following deps:

|$ sudo apt-get update && apt-get install -y python-all git bzip2 sudo 
wget zip $ sudo pip install ck $ sudo apt-get install -y libjpeg8 
libjpeg62-dev libfreetype6 libfreetype6-dev python-pillow $ sudo apt-get 
install -y build-essential automake autoconf libncurses-dev uuid-runtime 
m4 $ sudo apt-get install -y gcc g++ g++-multilib libc6-dev-i386 $ sudo 
apt-get install -y texinfo libisl-dev libcloog-isl-dev libmpc-dev 
libgmp-dev libmpfr-dev |
But maybe more importantly I suggest you to use another package which rebuilds old GMP, MPFR, etc
(because the new ones have different API):
|$ ck pull repo:reproduce-milepost-project $ ck install 
package:compiler-gcc-4.4.4-milepost-src-deps $ ck install 
package:compiler-ctuning-cc-2.5-plugins-src $ ck install 
package:compiler-ctuning-cc-2.5-src |
Please, tell me if it works.

You can also try Docker version:
|$ (sudo) docker run -it ctuning/ck-milepost-gcc-ubuntu16.04 $ cd `ck 
find demo:ctuning-cc` $ ./_use_ctuning_cc_directly_extract_features.sh|
||

I updated Readme with these steps ...

Hope it will be useful and thanks for your feedback,
Grigori

**Comment by hydai** [comment]
Hi,

Thank you for the information about this issue. I can build Milepost GCC from the dockerfile and extract features from C source code. My next step is to use Milepost GCC to recommend options for the programs.

Thank you for all your assistance. I really appreciate your help in resolving the problem.

Sincerely,
hydai

**Comment by gfursin** [comment]
Sure, you are welcome! Glad that it worked and good luck!
