### ISSUE TITLE
How to get the final features of the whole program?

### ISSUE THREAD

**Issue by coffezhou** [ctuning/reproduce-milepost-project#9]
Hi,
I use "_use_ctuning_cc_directly_extract_features.sh" to extract the features of a program, and it produces some function features files like "ici_features_function.xxxx.fre.ft". So how to get the final features of the whole program?  Simply add the function features? or the final features of the whole program should be generated by used according to the use scenario? I do not find it in the papers or I  missed. In addition, for some functions, "ici_features_function.xxxx.fre.ft" contains 57 features, while the others have 65 features. why? and what are the meanings of the extra features that do not present in the paper?

Thanks!

**Comment by gfursin** [comment]
Hi @coffezhou,
I actually stopped calculating final features for the whole program because it doesn't make much sense - it's like measuring the average temperature of all patients in the hospital...
Instead, I was talking the features of the hottest function (based on profiling) and used it for predictions. The reasoning is that it is likely that most performance improvements from global optimizations (compiler flags) will come from optimizing just this hot function, and hence we need to predict global optimizations based only on its features. 
However, if you still want to optimize other functions (for example by passing optimization flags to individual functions by pragmas or via plugins), you can use their features too ...
As for extra features (ft57-65), these were extensions by Jeremy Singer after MILEPOST project, and if I am correct, they are extracted only for FP-based programs (though I may be wrong - it was done nearly 8 years ago). You can find links with details about different groups of features in this interactive report: http://cKnowledge.org/rpi-crowd-tuning. Just search for "ft65"...
Hope it's of help and thank you for your interest!

**Comment by coffezhou** [comment]
Thank you very much!
